### ISSUE TITLE
「新規作成」出来なくなってしまいました……

### ISSUE THREAD

**Issue by snowdrops89** [code4history/MaplatEditor#41]
お久しぶりでした！
　0.6.0をインストールして、新規にデータを作成しようとした所、うまくいかなくなってしまいました……

**現象：**
　「新規作成」でメタデータ編集の必要事項を入力して「保存」を押しますと、固まってしまったような状態（画面のどこを押しても反応しない。文字入力部分にもフォーカスしない）になってしまいます。
　ただし、上部のメニューは動きますので、開発者ツールを表示させてみますと、こんなエラーが。
```
Uncaught (in promise) TypeError: Cannot read property 'getCompiled' of undefined
    at Object.<anonymous> (C:\Program Files\MaplatEditor\resources\app.asar\node_modules\@maplat\core\es5\source\store_handler.js:217:40)
    at step (C:\Program Files\MaplatEditor\resources\app.asar\node_modules\@maplat\core\es5\source\store_handler.js:32:23)
    at Object.next (C:\Program Files\MaplatEditor\resources\app.asar\node_modules\@maplat\core\es5\source\store_handler.js:13:53)
    at C:\Program Files\MaplatEditor\resources\app.asar\node_modules\@maplat\core\es5\source\store_handler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\MaplatEditor\resources\app.asar\node_modules\@maplat\core\es5\source\store_handler.js:3:12)
    at Object.histMap2Store (C:\Program Files\MaplatEditor\resources\app.asar\node_modules\@maplat\core\es5\source\store_handler.js:197:16)
    at Object.save (C:\Program Files\MaplatEditor\resources\app.asar\backend\src\mapedit.js:134:41)
    at electron/js2c/browser_init.js:233:7839
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:233:4244)
```

　他に、
```
mapedit.bundle.js:126 GET file:///C:/Program%20Files/MaplatEditor/resources/app.asar/html/tmbs/miyakonojyou04.jpg net::ERR_FILE_NOT_FOUND
```
　このようなエラーも大量に出ており、これは保存を押す前から出ているようなので関係あるか無いか分かりませんが、様々な地名の入ったjpgが無いよーと言われているようで、リンク先にミスがあるのかそれともこちらで他に何か必要な物があるのかしらと悩む所です。

　また、これも同じことに起因するのか別問題なのか分からないのですが、「地図画像登録」をすると、普通に登録の画面が開いてタイル分割中とかのバーが動くのですが、最後近くまで進んだ辺りで「地図画像登録でエラーが発生しました。」となってしまい登録が出来ません。

※これらの現象は、最近0.6.0をダウンロードして新規作成しようとした時に発生しましたが、一度アンインストールした後0.5.1、0.5.0とダウングレードしてみても直りませんでした。
　既に地図登録まで済んだデータで対応点を編集するのは問題がないので、実際のところいつからこうなのか分からないのです～＞＜（６を入れた結果発生したのか、５系の時からこうなのか、はたまた私のトコの環境に起因するのか？）

　お忙しい所すみませんが、ご確認をお願いします。

**Comment by kochizufan** [comment]
お久しぶりです

1. OSはWindowsですか？Macですか？MacならIntelですか、AppleSiliconでしょうか？
2. どういう環境でエラーが発生しているのか確かめたいので、もし見せたくないデータがあるとかでなければ、データを保存するフォルダをzipでまとめてギガファイル便などで送っていただくことは可能でしょうか？
3. 登録できない画像についても、送っていただけると助かります

**Comment by snowdrops89** [comment]
お疲れさまです。素早いご対応でありがとうございます☆

1、OSはWindows7の64bitです。７っていうのがアレですけれど、環境的に言えば逆に以前無事に出来ていた時から大きく変わってはおりません。
（無事に出来ていた時＝MaplatEditorのバージョンは0.4.1でした。今あるデータは全部0.4.1の時に新規登録した物で、0.5.0をインストールした時に新形式に自動変換された物なんですが、データ形式が違うっぽいので、0.4.1まではダウングレード試してみていないんですぅ）

2、「データを保存するフォルダ」とはどれのことでしょう。マイドキュメントに自動的に「MaplatEditor」フォルダが作成されて、そこに色々データが作成されるようですが、それでしょうか？
　新規の保存が一切出来ないので、あるのは以前登録したデータだけなのですが。（送るのは全然ＯＫです）
　ただ、このフォルダへの読み書きというよりは、出ているエラーの内容からすると、MaplatEditorのインストールフォルダの中にapp.asarってファイルがあって、コレへの読み書きがうまくいってないのかしらという印象です。

３、画像について言えば「どの画像でも」です。色々な画像で試しました。
　今あるデータと同じ、以前に登録出来た実績のある、2M程度の画像でもダメなのです。

**Comment by kochizufan** [comment]
https://drive.google.com/file/d/1VSui4Vrr_lN9D8QP0c_E-be0opSgPLKc/view?usp=sharing

こちらのバージョンを試してみてください。

> 「新規作成」でメタデータ編集の必要事項を入力して「保存」を押しますと、固まってしまったような状態（画面のどこを押しても反応しない。文字入力部分にもフォーカスしない）になってしまいます。

これは直ったと思います。

> このようなエラーも大量に出ており、これは保存を押す前から出ているようなので関係あるか無いか分かりませんが、様々な地名の入ったjpgが無いよーと言われているようで

これは無視してください

> また、これも同じことに起因するのか別問題なのか分からないのですが、「地図画像登録」をすると、普通に登録の画面が開いてタイル分割中とかのバーが動くのですが、最後近くまで進んだ辺りで「地図画像登録でエラーが発生しました。」となってしまい登録が出来ません。

これは全く分からないので、エラーが出る際にエラーの内容が開発者ツールに表示されるようにしました。
その開発者ツールの表示内容を教えてください。

**Comment by snowdrops89** [comment]
ありがとうございます！
保存は出来るようになりました。
地図画像の方はやはり登録出来ず、このようなエラーが出ています。
```
Error: ENOENT, No such file or directory 'C:\Users\あい\AppData\Local\Temp\MaplatEditor\tiles\0\0\0.jpg'
    at setSource (C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\lib\image.js:91:13)
    at Image.set (C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\lib\image.js:62:9)
    at C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\index.js:23:10)
    at extractor (C:\Program Files\MaplatEditor\resources\app.asar\backend\lib\ui_thumbnail.js:15:25)
    at Object.exports.make_thumbnail (C:\Program Files\MaplatEditor\resources\app.asar\backend\lib\ui_thumbnail.js:46:11)
    at Object.imageCutter (C:\Program Files\MaplatEditor\resources\app.asar\backend\src\mapupload.js:146:28)
mapedit.bundle.js:126 Error: ENOENT, No such file or directory 'C:\Users\あい\AppData\Local\Temp\MaplatEditor\tiles\0\0\0.png'
    at setSource (C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\lib\image.js:91:13)
    at Image.set (C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\lib\image.js:62:9)
    at C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Program Files\MaplatEditor\resources\app.asar.unpacked\assets\win\canvas\index.js:23:10)
    at extractor (C:\Program Files\MaplatEditor\resources\app.asar\backend\lib\ui_thumbnail.js:15:25)
    at Object.exports.make_thumbnail (C:\Program Files\MaplatEditor\resources\app.asar\backend\lib\ui_thumbnail.js:46:11)
    at Object.imageCutter (C:\Program Files\MaplatEditor\resources\app.asar\backend\src\mapupload.js:146:28)
```
よろしくお願いいたします。

**Comment by kochizufan** [comment]
1) 上のメニューで「設定(Setting)」を選び、データフォルダの項に書かれているフォルダ名を確認してください。
その値は「C:\Users\あい\AppData\Local\Temp\MaplatEditor」になっていますか？

2) また、「C:\Users\あい\AppData\Local\Temp\MaplatEditor」が本当に存在していますか？

3) 上記の「設定(Setting)」「データフォルダ」の設定を、日本語を含まないフォルダに変更してみてください。
それでもセーブできないでしょうか。

**Comment by snowdrops89** [comment]
１，データフォルダは、「C:\Users\あい\AppData\Local\Temp\MaplatEditor」ではありません。「C:\Users\あい\Documents\MaplatEditor」（マイドキュメント）になっていて、これは私が設定したというよりは、MaplatEditorを初回インストール時に作成されてデータフォルダに設定されており、ずっとそのまま使っています。

２，「C:\Users\あい\AppData\Local\Temp\MaplatEditor」は存在しています。これはTempフォルダで、ユーザーがデータを入れたりするような場所ではないのですが。
MaplatEditorをインストール時に自動的に作成されるようで、地図画像登録しようとするとフォルダやファイルも作成されているようです。

３，データフォルダを「C:\Maplat」とかにしてみましたが変わらず、また、「C:\Users\あい\AppData\Local\Temp\MaplatEditor」にもしてみましたが変わらずでした。

**Comment by snowdrops89** [comment]
あああぁぁっ、でっできました！！！
結論から言うと、やはりこちらの環境でした。
やはり、「C:\Users\あい\AppData\Local\Temp\MaplatEditor」が全角文字が入っているのが良くないようで（全く読み書き出来てないわけではなく、登録しようとしている地図画像なども入りはするのですが）
これはユーザー名なので、インストール先やデータフォルダをどこに作っても、必ずこのフォルダはここに作られ読みに行ってしまうため、windowsのユーザー名が全角文字だとなんとしてもダメなようで・・・アカウント名だけ変えてもフォルダ名自体はは変わらず、結局半角アルファベット名でもう一つ新規にアカウントを作成して試したところ出来ました☆
前は日本語名でも普通に出来ていたのですが・・・おそらく、データ形式の変わった５系からなのでしょうか。
すっかりお騒がせしてしまいまして、すみませんでした＞＜　ありがとうございました！

**Comment by kochizufan** [comment]
@snowdrops89 
同じURLからもういっぺんダウンロードしたバージョンを使ってみてください
日本語フォルダ下からでも読めるようになってるか確かめたいです

**Comment by snowdrops89** [comment]
試してみましたが、ダメでした～。
今回は、このようなエラーが出ています。
```
RangeError: byte length of Uint16Array should be a multiple of 2
    at new Uint16Array (<anonymous>)
    at extractor (C:\Program Files\MaplatEditor\resources\app.asar\backend\lib\ui_thumbnail.js:18:17)
    at Object.exports.make_thumbnail (C:\Program Files\MaplatEditor\resources\app.asar\backend\lib\ui_thumbnail.js:50:11)
    at Object.imageCutter (C:\Program Files\MaplatEditor\resources\app.asar\backend\src\mapupload.js:146:28)
```
そしてこれは、アルファベットのアカウントの方でも同現象でした。

**Comment by kochizufan** [comment]
@snowdrops89 何度もすみません、今度こそ直ってないかな...
同じURLからでお願いします

**Comment by snowdrops89** [comment]
おはようございます。
出来ました～！！！！
ありがとうございましたﾟ+.ヽ(≧▽≦)ﾉ.+ﾟ
